services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: oumate
      POSTGRES_PASSWORD: Oum%40psql.
      POSTGRES_DB: timetable_manager
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '6543:5432'

  web:
    build: .
    depends_on:
      - db
    ports:
      - '5000:5000'
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://oumate:Oum%40psql.@db:5432/timetable_manager
      FLASK_APP: app.py
    command: flask run --host=0.0.0.0

volumes:
  pgdata:
